version: '3'

services:
  online-clothing-store:
    container_name: online-clothing-store
    image: online-clothing-store:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

 
  


